### ISSUE TITLE
-bash: animate : commande introuvable

### ISSUE THREAD

**Issue by famibelle** [alexylem/jarvis-face#2]
Bonjour,
J'adore Jarvis, je voudrai savoir plus en détails comment je dois m'y prendre pour faire afficher l'UI.

**Comment by alexylem** [comment]
Bonjour @famibelle 
Il suffit d'installer le plugin, et il devrait s'afficher tout seul  (à condition d'avoir démarré l'environnement graphique).
Si tu rencontres des problèmes, ou des messages d'erreurs:
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by famibelle** [comment]
Merci, je vais lancer les commandes. Le plugin est installé, par contre, je suis en environment graphique Pixel, et quand je lance Jarvis depuis un terminal, la face ne s'affiche pas, d'où ma question initiale. Est ce que je dois faire une commande spécifique pour avec le visage ?

**Comment by alexylem** [comment]
Non ça devrait s'afficher tout seul. As tu une erreur dans la console ? Peux-tu nous coller le terminal en mode troubleshooting ? Merci.

**Comment by famibelle** [comment]
le voici 
http://asciinema.org/a/40owuig2evz2bxbpr65ssmk8j

**Comment by alexylem** [comment]
Ok très bien.
Peux-tu me donner le résultat des commandes suivantes (depuis l'environnement graphique bien entendu, et depuis le dossier jarvis):
```shell
$> w
$> cat plugins/jarvis-face/config.sh
$> animate --version
$> animate -verbose plugins/jarvis-face/faces/fluorescent/neutral/blinking.gif
```
Merci.

**Comment by famibelle** [comment]
et voila
```bash
pi@tchouri:~/jarvis $ w
 20:37:14 up 1 min,  3 users,  load average: 1,69, 0,67, 0,25
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
pi       tty1                      20:17   20:13   0.83s  0.69s -bash
pi       :0       :0               20:17   ?xdm?  54.42s  0.43s /usr/bin/lx
pi@tchouri:~/jarvis $ cat plugins/jarvis-face/config.sh
pi@tchouri:~/jarvis $ animate --version
-bash: animate : commande introuvable
pi@tchouri:~/jarvis $ animate -verbose plugins/jarvis-face/faces/fluorescent/neutral/blinking.gif
-bash: animate : commande introuvable
```

**Comment by alexylem** [comment]
Oula... ton fichier de config est vide? Et animate ne semble pas être installé non plus.

A mon avis, désinstalle puis réinstalle ton plugin:
1. Menu plugins / Installed / Face / Uninstall
2. Menu plugins / Search / Face / Install

**Comment by famibelle** [comment]
ok je me disais aussi, d'ailleurs est ce que animate est un package raspbian ?

**Comment by alexylem** [comment]
Il fait partie de `imagemagick`. S'installe automatiquement avec le plugin.

**Comment by famibelle** [comment]
Merci, 
Entretemps, (hier soir) j'ai eu un SD corrupt :-(

**Comment by famibelle** [comment]
Bonsoir, 
Je pense que le problème venait d'un SD Card corrupt. 
J'ai remis Raspbian sur une carte neuve et tout marche
